### ISSUE TITLE
Room sharing

### ISSUE THREAD

**Issue by zarp-dev** [cinnyapp/cinny#108]
#### Is your feature request related to a problem? Please describe.
It is important that the user can get a room link in order to invite people to the room.

#### Describe the solution you'd like
![Screenshot 2021-09-18 at 16 21 20](https://user-images.githubusercontent.com/65812041/133892065-00252ecc-4ab2-40c4-b95e-c3906f183cb7.png)

This is how it is implemented in Element:
![Screenshot 2021-09-18 at 17 22 31](https://user-images.githubusercontent.com/65812041/133892013-02150ff3-03f3-4a34-8526-ec3b875fc39b.png)

This is how it is implemented in Discord:
![image](https://user-images.githubusercontent.com/65812041/133923033-8f6f8f4f-a547-483a-80a2-81aab2044c12.png)

**Comment by vwkd** [comment]
Not in favor of yet another pop up that blocks the entire UI.

How about a “copy room URL” under the room options menu (three dots)? Nobody cares how the actual URL looks like, so there is no reason to show it in the UI.

Inviting people to a room could be done as part of more advanced commands in a command modal (#129) instead of adding yet more nested UIs. I’m thinking a command like `invite @user to #room` where everything nicely autocompletes. There are more advantages to it like being much faster, universally accessible, etc. See https://github.com/ajbura/cinny/issues/129#issuecomment-937692923

**Comment by kfiven** [comment]
Require #70

**Comment by franzihei** [comment]
Came here to open exactly this as an issue! Currently, afaik, there is no way to share a link to a certain room / find the room link anywhere, correct? Or am I missing something?
